"""Regenerate frontend/public/sitemap.xml.

    backend/venv/bin/python -m backend.sitemap

Run it whenever a league is added or renamed. The league list comes from
backend/scraper/config.py, the single source of truth, rather than being typed
into the XML, where a new league would silently never be listed.
"""
import re
import unicodedata
from pathlib import Path

from backend.scraper.config import LEAGUES

HOST = "https://progettoolanda.it"
OUT = Path(__file__).resolve().parent.parent / "frontend" / "public" / "sitemap.xml"

# The four legal pages as `.html`, as the app links them: the bare /privacy
# and /terms work too (netlify.toml), but one canonical form per page.
STATIC = ["/", "/privacy.html", "/privacy.en.html", "/terms.html", "/terms.en.html"]
# utils/routes.js, SECTION paths.
SECTIONS = ["/hot-matches", "/market-moves", "/winning-factor", "/bonus-planner"]


def slug(value: str) -> str:
    """utils/routes.js `slug()`, exactly: the app resolves a league URL by
    slugifying its league names and comparing, so these must agree."""
    s = unicodedata.normalize("NFKD", value)
    s = "".join(c for c in s if not unicodedata.combining(c)).lower()
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-")


HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by `python -m backend.sitemap` from backend/scraper/config.py.
  Edit that script, not this file.

  The site root, the four legal pages (static files, render with JS off), the
  four sections and one root per league. League STANDINGS are indexable but
  not listed yet.

  NEVER a team or a match URL: they carry meta robots=noindex, because a match
  is stale within the week and thousands of thin URLs is a liability - and a
  noindex page in a sitemap is a contradiction Search Console reports.

  Sections and leagues render from the API. With it asleep they show the
  load-failure panel, which carries the site's prose (components/Fallback);
  Search Console's live test of /league/serie-a on 2026-09-26 got no data at
  all, so check that test again before reading anything into their indexing.

  No <lastmod>/<changefreq>/<priority>: Google ignores the latter two, and a
  lastmod nobody keeps accurate is worse than none. ABSOLUTE urls, so they
  carry the host - see HOST in the script, and robots.txt / index.html's og:.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
"""


def main() -> None:
    leagues = [f"/league/{slug(cfg['name'])}" for cfg in LEAGUES.values()]
    paths = STATIC + SECTIONS + leagues
    assert len(set(paths)) == len(paths), "two leagues slugify to the same URL"
    body = "".join(f"  <url><loc>{HOST}{p}</loc></url>\n" for p in paths)
    OUT.write_text(HEADER + body + "</urlset>\n", encoding="utf-8")
    print(f"{OUT.relative_to(OUT.parents[2])}: {len(paths)} urls "
          f"({len(STATIC)} static, {len(SECTIONS)} sections, {len(leagues)} leagues)")


if __name__ == "__main__":
    main()
