import React from 'react';
import { X, Trash2, Printer, Trophy } from 'lucide-react';

const BetSlipModal = ({ isOpen, onClose, bets, onRemove, onClear }) => {
    if (!isOpen) return null;

    const handlePrint = () => {
        const printContent = document.getElementById('bet-slip-content').innerHTML;

        // Create a new window for printing
        const printWindow = window.open('', '', 'height=600,width=800');
        printWindow.document.write('<html><head><title>Bet Slip</title>');
        printWindow.document.write('<style>');
        printWindow.document.write(`
            body { font-family: sans-serif; padding: 20px; color: black; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            .header { display: flex; align-items: center; gap: 10px; margin-bottom: 20px; border-bottom: 2px solid #eee; padding-bottom: 10px; }
            .logo { width: 40px; height: 40px; object-fit: contain; }
            .app-name { font-size: 20px; font-weight: bold; color: #000; }
            .gradient-text {
                background: linear-gradient(to right, #34d399, #22d3ee) !important;
                -webkit-background-clip: text !important;
                -webkit-text-fill-color: transparent !important;
                background-clip: text !important;
                color: transparent !important;
                -webkit-print-color-adjust: exact !important;
                print-color-adjust: exact !important;
            }
            h2 { text-align: center; border-bottom: 2px solid #eee; padding-bottom: 10px; }
            .bet-item { border-bottom: 1px solid #eee; padding: 10px 0; display: flex; justify-content: space-between; }
            .game { font-weight: bold; }
            .selection { color: #059669; font-weight: bold; }
            .stat-label { font-size: 10px; text-transform: uppercase; color: #666; margin-right: 5px; }
            .footer { margin-top: 20px; text-align: center; font-size: 12px; color: #666; }
            .no-print { display: none !important; }
        `);
        printWindow.document.write('</style></head><body>');

        // Add Header with Logo and Name
        const logoUrl = window.location.origin + '/logo.png';
        printWindow.document.write(`
            <div class="header">
                <img src="${logoUrl}" class="logo" alt="Logo" />
                <span class="app-name">Progetto <span class="gradient-text">Olanda 2.0</span></span>
            </div>
        `);

        printWindow.document.write(printContent);
        printWindow.document.write('<div class="footer">Generated by Progetto Olanda 2.0</div>');
        printWindow.document.close();

        printWindow.focus();
        setTimeout(() => {
            printWindow.print();
        }, 250);
    };

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-zinc-900 border border-white/10 rounded-2xl w-full max-w-md shadow-2xl overflow-hidden flex flex-col max-h-[80vh]">
                {/* Header */}
                <div className="p-4 border-b border-white/10 flex items-center justify-between bg-zinc-950/50">
                    <h3 className="text-lg font-bold text-white flex items-center gap-2">
                        <Trophy className="w-5 h-5 text-emerald-400" />
                        Your Bet Slip
                    </h3>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-white/10 rounded-lg transition-colors text-zinc-400 hover:text-white"
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* Content */}
                <div className="p-4 overflow-y-auto custom-scrollbar flex-grow" id="bet-slip-content">
                    {bets.length === 0 ? (
                        <div className="text-center py-8 text-zinc-500">
                            <p>No bets added yet.</p>
                            <p className="text-xs mt-1">Select matches to build your slip.</p>
                        </div>
                    ) : (
                        <div className="space-y-3">
                            {bets.map((bet, index) => (
                                <div key={index} className="bet-item bg-white/5 rounded-xl p-3 border border-white/5 flex items-center justify-between group">
                                    <div>
                                        <div className="game font-bold text-white text-sm">{bet.game}</div>
                                        <div className="text-xs text-zinc-400 mt-1 flex items-center gap-2">
                                            <span className="bg-white/10 px-1.5 py-0.5 rounded text-[10px] uppercase font-bold text-zinc-300 stat-label">
                                                {bet.team !== 'total' ? `${bet.team} ` : ''}{bet.stat?.replace(/_/g, ' ') || 'Stat'}
                                            </span>
                                            <span className="selection text-emerald-400 font-mono font-bold text-sm">
                                                {bet.option === 'O' ? 'Over' : 'Under'} {bet.value}
                                            </span>
                                        </div>
                                    </div>
                                    <button
                                        onClick={() => onRemove(bet.game)}
                                        className="p-2 text-zinc-500 hover:text-red-400 hover:bg-red-500/10 rounded-lg transition-all opacity-0 group-hover:opacity-100 no-print"
                                        title="Remove"
                                    >
                                        <Trash2 className="w-4 h-4" />
                                    </button>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="p-4 border-t border-white/10 bg-zinc-950/50 flex gap-3">
                    <button
                        onClick={onClear}
                        disabled={bets.length === 0}
                        className="flex-1 py-2.5 rounded-xl font-bold text-sm uppercase tracking-wide transition-all border border-white/10 text-zinc-400 hover:text-white hover:bg-white/5 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        Clear
                    </button>
                    <button
                        onClick={handlePrint}
                        disabled={bets.length === 0}
                        className="flex-[2] py-2.5 rounded-xl font-bold text-sm uppercase tracking-wide transition-all bg-emerald-500 hover:bg-emerald-400 text-white shadow-[0_0_20px_rgba(16,185,129,0.2)] disabled:opacity-50 disabled:cursor-not-allowed disabled:shadow-none flex items-center justify-center gap-2"
                    >
                        <Printer className="w-4 h-4" />
                        Print to PDF
                    </button>
                </div>
            </div>
        </div>
    );
};

export default BetSlipModal;
